#server port
server:
  port: 7001

dubbo:
  application:
    name: @project.name@

spring:
  security:
    user:
      name: admin
      password: admin
  profiles:
    include: common

system:
  group:
    name: system-group
