#server port
server:
  port: ${random.int[1000,9999]}

#dubbo config
dubbo:
  application:
    name: role-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
