#server port
server:
  port: 7004

dubbo:
  application:
    name: @project.name@

spring:
  profiles:
    include: common
seata:
  application-id: easyray-team-provider
  tx-service-group: easyray-team-provider #也用来生成nacos中的dataId
