#server port
server:
  port: 7004

dubbo:
  application:
    name: @project.name@

spring:
  profiles:
    include: common
seata:
  application-id: @project.name@
  tx-service-group: @project.name@ #也用来生成nacos中的dataId
