#db config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/easyray?useUnicode=true&characterEncoding=utf8
    username: easyray
    password: easyray
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

#dubbo config
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
  consumer:
    retries: -1
    timeout: -1

#actable config
actable:
  database:
    type: mysql
  model:
    pack: com.easyray
  create:
    mode: update
  execute:
    sql: true
  print:
    sql: true

#log
logging:
  file:
    path: .
  level:
    com.easyray: debug
