nacos:
  host: 192.168.10.11:8848

#db config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.240:3309/wyy_easyray?useUnicode=true&characterEncoding=utf8
    username: wangyuyuan
    password: wangyuyuan
    type: com.alibaba.druid.pool.DruidDataSource
  #redis
  redis:
    host: 192.168.10.11
    port: 6379
#utf-8
server:
  servlet:
    encoding:
      charset: UTF-8

#dubbo config
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}
  consumer:
    retries: -1
    timeout: -1

#actable config
actable:
  database:
    type: mysql
  model:
    pack: com.easyray
  create:
    mode: update
  execute:
    sql: true
  print:
    sql: true

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#seata config
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.host}
  config:
    type: nacos
    nacos:
      server-addr: ${nacos.host}
  tx-group-value: default
