server:
  servlet:
    context-path: /team
  port: 7003

dubbo:
  application:
    name: @project.name@

spring:
  profiles:
    include: common,default
seata:
  application-id: easyray-team-web
  tx-service-group: easyray-team-web #也用来生成nacos中的dataId
