server:
  servlet:
    context-path: /team
  port: 7003

dubbo:
  application:
    name: @project.name@

spring:
  profiles:
    include: common
seata:
  application-id: @project.name@
  tx-service-group: @project.name@ #也用来生成nacos中的dataId
